
# set the programming language to java:
language: java

# test for these JDK versions and environments
jdk:
   - oraclejdk8

script: 
   - mvn clean verify
   
#after_success:
#   - mvn clean test jacoco:report coveralls:report