# Root rights are required during the build process:
sudo: required

# Set the programming language to java:
language: java

# Set JDK versions to Oracle Java 8:
jdk:
   - oraclejdk8

# Build step:
script: 
   - mvn clean verify

# After a successful build generate a coverage report and commit it to coveralls:   
after_success:
   - mvn clean test jacoco:report coveralls:report